# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/Electronic-Piano-Learning-Machine/Electronic-Piano-Learning-Machine.srcs/sources_1/ip/clk_gen_1/clk_gen.xci
# IP: The module: 'clk_gen' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Electronic-Piano-Learning-Machine/Electronic-Piano-Learning-Machine.gen/sources_1/ip/clk_gen_1/clk_gen_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_gen'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: d:/Electronic-Piano-Learning-Machine/Electronic-Piano-Learning-Machine.gen/sources_1/ip/clk_gen_1/clk_gen.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_gen'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: d:/Electronic-Piano-Learning-Machine/Electronic-Piano-Learning-Machine.gen/sources_1/ip/clk_gen_1/clk_gen_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_gen'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: d:/Electronic-Piano-Learning-Machine/Electronic-Piano-Learning-Machine.srcs/sources_1/ip/clk_gen_1/clk_gen.xci
# IP: The module: 'clk_gen' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Electronic-Piano-Learning-Machine/Electronic-Piano-Learning-Machine.gen/sources_1/ip/clk_gen_1/clk_gen_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_gen'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: d:/Electronic-Piano-Learning-Machine/Electronic-Piano-Learning-Machine.gen/sources_1/ip/clk_gen_1/clk_gen.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_gen'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: d:/Electronic-Piano-Learning-Machine/Electronic-Piano-Learning-Machine.gen/sources_1/ip/clk_gen_1/clk_gen_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_gen'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
