
set_property PACKAGE_PIN P17 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports speaker]

set_property PACKAGE_PIN F6 [get_ports {led_out[7]}]
set_property PACKAGE_PIN G4 [get_ports {led_out[6]}]
set_property PACKAGE_PIN G3 [get_ports {led_out[5]}]
set_property PACKAGE_PIN H4 [get_ports {led_out[3]}]
set_property PACKAGE_PIN J3 [get_ports {led_out[2]}]
set_property PACKAGE_PIN J2 [get_ports {led_out[1]}]
set_property PACKAGE_PIN K2 [get_ports {led_out[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_out[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_out[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_out[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_out[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_out[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_out[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_out[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_out[0]}]

set_property PACKAGE_PIN T1 [get_ports audio]
set_property PACKAGE_PIN H17 [get_ports speaker]
set_property IOSTANDARD LVCMOS33 [get_ports audio]




set_property PACKAGE_PIN B4 [get_ports {tub_control1[7]}]
set_property PACKAGE_PIN A4 [get_ports {tub_control1[6]}]
set_property PACKAGE_PIN A3 [get_ports {tub_control1[5]}]
set_property PACKAGE_PIN B1 [get_ports {tub_control1[4]}]
set_property PACKAGE_PIN A1 [get_ports {tub_control1[3]}]
set_property PACKAGE_PIN B3 [get_ports {tub_control1[2]}]
set_property PACKAGE_PIN B2 [get_ports {tub_control1[1]}]
set_property PACKAGE_PIN D5 [get_ports {tub_control1[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {tub_control1[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {tub_control1[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {tub_control1[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {tub_control1[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {tub_control1[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {tub_control1[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {tub_control1[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {tub_control1[0]}]
set_property PACKAGE_PIN G2 [get_ports {tub_select1[3]}]
set_property PACKAGE_PIN C2 [get_ports {tub_select1[2]}]
set_property PACKAGE_PIN C1 [get_ports {tub_select1[1]}]
set_property PACKAGE_PIN H1 [get_ports {tub_select1[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {tub_select1[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {tub_select1[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {tub_select1[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {tub_select1[0]}]

set_property PACKAGE_PIN D4 [get_ports {tub_control2[7]}]
set_property PACKAGE_PIN E3 [get_ports {tub_control2[6]}]
set_property PACKAGE_PIN D3 [get_ports {tub_control2[5]}]
set_property PACKAGE_PIN F4 [get_ports {tub_control2[4]}]
set_property PACKAGE_PIN F3 [get_ports {tub_control2[3]}]
set_property PACKAGE_PIN E2 [get_ports {tub_control2[2]}]
set_property PACKAGE_PIN D2 [get_ports {tub_control2[1]}]
set_property PACKAGE_PIN H2 [get_ports {tub_control2[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {tub_control2[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {tub_control2[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {tub_control2[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {tub_control2[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {tub_control2[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {tub_control2[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {tub_control2[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {tub_control2[0]}]
set_property PACKAGE_PIN G1 [get_ports {tub_select2[3]}]
set_property PACKAGE_PIN F1 [get_ports {tub_select2[2]}]
set_property PACKAGE_PIN E1 [get_ports {tub_select2[1]}]
set_property PACKAGE_PIN G6 [get_ports {tub_select2[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {tub_select2[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {tub_select2[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {tub_select2[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {tub_select2[0]}]

set_property IOSTANDARD LVCMOS33 [get_ports left_button]
set_property IOSTANDARD LVCMOS33 [get_ports right_button]
set_property PACKAGE_PIN V1 [get_ports left_button]
set_property PACKAGE_PIN R11 [get_ports right_button]

set_property IOSTANDARD LVCMOS33 [get_ports up_button]
set_property IOSTANDARD LVCMOS33 [get_ports down_button]
set_property PACKAGE_PIN J4 [get_ports {led_out[4]}]
set_property PACKAGE_PIN U4 [get_ports up_button]
set_property PACKAGE_PIN R17 [get_ports down_button]
